### ISSUE TITLE
Query - Cross-region and custom card for e-Reader

### ISSUE THREAD

**Issue by ehsanh06** [notblisy/RUBYSAPPHIREDLC#3]
Hey @notblisy , thanks for the awesome work on this - I recently bought a Japanese e-Reader (AGB-014) inspired by your DLC for Sapphire/Ruby video for the e-Reader and whilst I have a Japanese-copy of Pokemon Sapphire, I also have a PAL/EUR version of Pokemon Emerald and Leaf Green. My questions are as follows:

1. Is it possible to print say an English event and be able to scan this on the Japanese e-Reader and transfer this onto one of the PAL/EUR versions of E/LF?

2. In the case that there isn't any plans, if I wanted to build some custom events for the e-Reader, what prerequisites would need considering? (Presumably knowing Assembly would help!)

**Comment by notblisy** [comment]
In regards to point 1, you can do that but it requires you to dissemble and re-build the card by setting the language in the compiler to 2, for Japanese, and also deleting any english text I placed in there. 

As for two, I suggest giving this thread a go-over: https://www.pokecommunity.com/showthread.php?t=455241

It explains how to work with the repository Hacky and Paccy built. 

After that, take a look at this: https://github.com/pret/pokeruby/blob/28b53dc44be33e5e5b419ff6909cc8b34df6b4ab/include/macros/event.inc#L4

This is all of the supported commands for the RS Scripting language, you'll have to use it first before learning ASM.

Lastly, for the ASM stuff, I used :https://problemkaputt.de/gbatek.htm#thumbinstructionsummary

As a reference. 

Feel free to join my discord, it has an E-Reader section once you read the rules. I'm more than happy to help others work on an e-card project.
