### ISSUE TITLE
Japanese Ruby version cannot receive EON ticket

### ISSUE THREAD

**Issue by DittoLink** [notblisy/RUBYSAPPHIREDLC#4]
I use your E-Reader raw file "EONjpn.raw" to inject EON ticket to japanese ruby version but it display "このデータは このバージョンではしょう できません".
![eonticket](https://github.com/notblisy/RUBYSAPPHIREDLC/assets/43905487/e180f55d-60ed-4bc0-9f21-2a7c6df0b235)

**Comment by notblisy** [comment]
I think it was just a case of incorrect file upload, it's fixed now. Sorry I didn't notice this sooner.
